#spring.profiles.active=@profileActive@
#spring.profiles.active=mysql
#server:
#   port: 9020

certficat:
   ssl:
      client: /config/ecommerce-client.jks
      
server:
   #address: localhost
   port: 9021
   servlet:
      contextPath: /microservice-produits

#défini l'encodage pour data.sql
## Configs de la BD
spring:
   application:
      name: MICRO-SERVICE-PRODUITS-MYSQL
   sleuth:
      sampler:
         percentage: 1.0   
   datasource:
      sql-script-encoding: UTF-8
      url: jdbc:mysql://appsDB:3306/produits-db?useSSL=false&allowPublicKeyRetrieval=true
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: helloworld

## JPA/HIBERNATE      
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

      showSql: false
      hibernate:
         ddlAuto: update
         
## Eureka Client   
   cloud:
      ignoredInterfaces:
        - eno.*
        - virbr.*

   


#######################################################
######### Découverte/Enregistrement Eureka    #########
#######################################################
eureka:
   client:
      serviceUrl:
         defaultZone: https://eureka-server-conteneur:8761/eureka/
   instance:
      hostname: produits-conteneur-mysql
      preferIpAddress: true
      instanceId: ${eureka.instance.hostname}:${spring.application.name}:${server.port} 

#######################################################
####### Monitoring dans Spring Admin ########
#######################################################
spring.boot.admin.client:
   url: http://admin-server-conteneur:9095
   #instance:
   #   name: ${spring.application.name}
   #   preferIp: true 
   
   
   
   #instance:
   #   metadata:
   #     user.name: ${spring.security.user.name}
   #     user.password: ${spring.security.user.password}

management:
   endpoints:
      web:
         exposure:
           include: "*"  
   endpoint:
      health:
         show-details: ALWAYS


#spring.boot.admin.client.url= http://localhost:9095
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details= always
#spring.boot.admin.client.username=client
#spring.boot.admin.client.password=client
